INSERT INTO USER (ID, BIRTHDATE, CITY, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, SIGN_IN_DATE)
    VALUES (1, '1990-12-01', 'Lille', 'jean.paul@mail', 'Jean', 'Paul', '', '0123456789', CURRENT_TIMESTAMP);
INSERT INTO USER (ID, BIRTHDATE, CITY, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, SIGN_IN_DATE)
    VALUES (2, '1989-11-02', 'Paris', 'pierre.dupont@mail.com', 'Pierre', 'Dupont', '', '0658745636', CURRENT_TIMESTAMP);
INSERT INTO USER (ID, BIRTHDATE, CITY, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, SIGN_IN_DATE)
    VALUES (3, '1988-10-03', 'New York', 'john.doe@protonmail.com', 'John', 'Doe', '', '0487963521', CURRENT_TIMESTAMP);

INSERT INTO FRIENDSHIP (FIRST_USER_ID, SECOND_USER_ID, FRIENDSHIP_DATE)
    VALUES (1, 2, CURRENT_TIMESTAMP);

INSERT INTO INVITATION (FIRST_USER_ID, SECOND_USER_ID, INVITATION_DATE)
    VALUES (1, 3, CURRENT_TIMESTAMP);